[package]
name = "retry"
version = "0.2.0"
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Retry an operation until a condition is true."
license = "MIT"
readme = "README.md"
keywords = ["utility", "utilities"]
repository = "https://github.com/jimmycuadra/retry"
homepage = "https://github.com/jimmycuadra/retry"
