[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Retry an operation until a condition is true."
documentation = "https://jimmycuadra.github.io/retry/retry/"
homepage = "https://github.com/jimmycuadra/retry"
keywords = ["utility", "utilities"]
license = "MIT"
name = "retry"
readme = "README.md"
repository = "https://github.com/jimmycuadra/retry"
version = "0.4.0"

[dependencies]
rand = "0.3.14"
